import { useAppContext } from "../context";

export function useScheduleController() {
	const ctx = useAppContext();

	return {
		meds: ctx.meds,
		loading: ctx.loading,
		settings: ctx.settings,
		settingsLoading: ctx.settingsLoading,
		coverage: ctx.coverage,
		coverageByMed: ctx.coverageByMed,
		depletionByMed: ctx.depletionByMed,
		stockThresholds: ctx.stockThresholds,
		scheduleDays: ctx.scheduleDays,
		setScheduleDays: ctx.setScheduleDays,
		showPastDays: ctx.showPastDays,
		setShowPastDays: ctx.setShowPastDays,
		showFutureDays: ctx.showFutureDays,
		setShowFutureDays: ctx.setShowFutureDays,
		pastDays: ctx.pastDays,
		todayDay: ctx.todayDay,
		futureDays: ctx.futureDays,
		takenDoses: ctx.takenDoses,
		dismissedDoses: ctx.dismissedDoses,
		skippedDoses: ctx.skippedDoses,
		markDoseTaken: ctx.markDoseTaken,
		markDoseSkipped: ctx.markDoseSkipped,
		undoDoseTaken: ctx.undoDoseTaken,
		undoDoseSkipped: ctx.undoDoseSkipped,
		journalEditorOpen: ctx.journalEditorOpen,
		journalHistoryOpen: ctx.journalHistoryOpen,
		journalTargetDoseId: ctx.journalTargetDoseId,
		journalEvent: ctx.journalEvent,
		journalEventLoading: ctx.journalEventLoading,
		journalEventSaving: ctx.journalEventSaving,
		journalEventDeleting: ctx.journalEventDeleting,
		journalEventError: ctx.journalEventError,
		journalHistoryEntries: ctx.journalHistoryEntries,
		journalHistoryFilters: ctx.journalHistoryFilters,
		journalHistoryLoading: ctx.journalHistoryLoading,
		journalHistoryError: ctx.journalHistoryError,
		openJournalEditor: ctx.openJournalEditor,
		closeJournalEditor: ctx.closeJournalEditor,
		saveJournalNote: ctx.saveJournalNote,
		deleteJournalNote: ctx.deleteJournalNote,
		openJournalHistory: ctx.openJournalHistory,
		closeJournalHistory: ctx.closeJournalHistory,
		setJournalHistoryFilters: ctx.setJournalHistoryFilters,
		reloadJournalHistory: ctx.reloadJournalHistory,
		reopenJournalHistoryEntry: ctx.reopenJournalHistoryEntry,
		manuallyCollapsedDays: ctx.manuallyCollapsedDays,
		manuallyExpandedDays: ctx.manuallyExpandedDays,
		toggleDayCollapse: ctx.toggleDayCollapse,
		missedPastDoseIds: ctx.missedPastDoseIds,
		getDayStockStatus: ctx.getDayStockStatus,
		getDoseId: ctx.getDoseId,
		isDoseTakenAutomatically: ctx.isDoseTakenAutomatically,
		openMedDetail: ctx.openMedDetail,
		openUserFilter: ctx.openUserFilter,
		openScheduleLightbox: ctx.openScheduleLightbox,
		loadMeds: ctx.loadMeds,
		loadSettings: ctx.loadSettings,
	};
}
