name: Add to Project

on:
  issues:
    types: [opened, labeled]

permissions: {}

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: ${{ vars.PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: enhancement, bug, triage
          label-operator: OR
